
  application:
    # dev开发环境 test测试环境 prod线上环境
    mode: dev
    # 服务器ip，默认使用 0.0.0.0
    host: 0.0.0.0
    # 服务名称
    port: 8000 # 服务端口号
    # 项目名
    appName: ApisAdmin
  logger:
    # 日志存放路径
    path: temp/logs
  jwt:
    # token 密钥，生产环境时及的修改
    secret: apis-builder
    # token 过期时间 单位：秒
    expire: 3600
  database:
    # 数据库类型 mysql，sqlite3， postgres
    driver: mysql
    # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    source: user:password@tcp(127.0.0.1:3306)/apis-admin?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
#  databases:
#    'locaohost:8000':
#      driver: mysql
#        # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
#        source: user:password@tcp(127.0.0.1:3306)/dbname?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
#      registers:
#        - sources:
#            - user:password@tcp(127.0.0.1:3306)/dbname?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
